export const lightCodeTheme = {
  hljs: {
    display: "block",
    overflowX: "auto",
    padding: 0,
    background: "transparent",
    color: "#1f2937",
  },
  "hljs-comment": { color: "#9ca3af", fontStyle: "italic" },
  "hljs-quote": { color: "#9ca3af", fontStyle: "italic" },
  "hljs-keyword": { color: "#7c3aed" },
  "hljs-selector-tag": { color: "#7c3aed" },
  "hljs-literal": { color: "#b45309" },
  "hljs-built_in": { color: "#b45309" },
  "hljs-number": { color: "#b45309" },
  "hljs-regexp": { color: "#b45309" },
  "hljs-string": { color: "#15803d" },
  "hljs-meta-string": { color: "#15803d" },
  "hljs-title": { color: "#0369a1" },
  "hljs-section": { color: "#0369a1" },
  "hljs-name": { color: "#0369a1" },
  "hljs-selector-id": { color: "#0369a1" },
  "hljs-attr": { color: "#0369a1" },
  "hljs-symbol": { color: "#0369a1" },
  "hljs-bullet": { color: "#0369a1" },
  "hljs-subst": { color: "#1f2937" },
  "hljs-meta": { color: "#9ca3af" },
  "hljs-tag": { color: "#1f2937" },
  "hljs-link": { color: "#0369a1" },
  "hljs-emphasis": { fontStyle: "italic" },
  "hljs-strong": { fontWeight: "700" },
  "hljs-variable": { color: "#1f2937" },
  "hljs-template-variable": { color: "#1f2937" },
  "hljs-doctag": { color: "#9ca3af" },
};

export const darkCodeTheme = {
  hljs: {
    display: "block",
    overflowX: "auto",
    padding: 0,
    background: "transparent",
    color: "#e5e7eb",
  },
  "hljs-comment": { color: "#6b7280", fontStyle: "italic" },
  "hljs-quote": { color: "#6b7280", fontStyle: "italic" },
  "hljs-keyword": { color: "#c4b5fd" },
  "hljs-selector-tag": { color: "#c4b5fd" },
  "hljs-literal": { color: "#fcd34d" },
  "hljs-built_in": { color: "#fcd34d" },
  "hljs-number": { color: "#fcd34d" },
  "hljs-regexp": { color: "#fcd34d" },
  "hljs-string": { color: "#86efac" },
  "hljs-meta-string": { color: "#86efac" },
  "hljs-title": { color: "#7dd3fc" },
  "hljs-section": { color: "#7dd3fc" },
  "hljs-name": { color: "#7dd3fc" },
  "hljs-selector-id": { color: "#7dd3fc" },
  "hljs-attr": { color: "#7dd3fc" },
  "hljs-symbol": { color: "#7dd3fc" },
  "hljs-bullet": { color: "#7dd3fc" },
  "hljs-subst": { color: "#e5e7eb" },
  "hljs-meta": { color: "#6b7280" },
  "hljs-tag": { color: "#e5e7eb" },
  "hljs-link": { color: "#7dd3fc" },
  "hljs-emphasis": { fontStyle: "italic" },
  "hljs-strong": { fontWeight: "700" },
  "hljs-variable": { color: "#e5e7eb" },
  "hljs-template-variable": { color: "#e5e7eb" },
  "hljs-doctag": { color: "#6b7280" },
};
